apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-2-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-2-backend
  template:
    metadata:
      labels:
        app: devops-2-backend
    spec:
      containers:
        - name: devops-2-backend
          image: devops-2-backend
          ports:
            - containerPort: 8080
          env:
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DEBUG
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SECRET_KEY